### **Задание на повторение материала

In [1]:
import numpy as np
import pandas as pd

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)
a3 = a.reshape(2, 6)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [6]:
a1 = a.reshape(3, -1)
a2 = a.reshape(-1, 3)
a3 = a.reshape(2, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(12, -1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [8]:
a5.ndim

2

Нельзя, так как каждый элемент такого массива(строка) состоит снова из массива.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [10]:
x = np.random.randn(3, 4)

x

array([[ 0.83593189, -0.46997338, -0.56413684,  0.22289146],
       [-0.80862303, -0.02920023, -0.04037117,  0.56349771],
       [ 0.10487292, -0.19613432,  0.71875688, -1.29710368]])

In [83]:
y = x.flatten()

print(y)

[ 0.83593189 -0.46997338 -0.56413684  0.22289146 -0.80862303 -0.02920023
 -0.04037117  0.56349771  0.10487292 -0.19613432  0.71875688 -1.29710368]


In [84]:
x.size == y.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [15]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [17]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Не понял в чем разница

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [30]:
a = np.zeros([2, 2])
b = np.ones([3, 2])
a, b

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [31]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
c.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [37]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
A = a.reshape((4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [71]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [72]:
np.random.seed(42)
np.random.rand()

0.3745401188473625

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [73]:
c = np.random.randint(1, 16, (1, 16))
c

array([[13, 15, 11,  8, 13,  5,  7, 10,  3,  7, 11, 11,  8,  5,  4,  8]])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [74]:
C = c.reshape((4, 4))
C

array([[13, 15, 11,  8],
       [13,  5,  7, 10],
       [ 3,  7, 11, 11],
       [ 8,  5,  4,  8]])

In [69]:
D = B + C * 10 
D

array([[ 15,  94,  53,  62],
       [ 24, 160, 136, 222],
       [ 93, 186, 239, 332],
       [102, 212, 292, 422]])

In [78]:
o = np.linalg.det(D)
r = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(f'Определитель: {o}\nРанг: {r}\nОбратная матрица:\n{D_inv}')

Определитель: -3720000.000000005
Ранг: 4
Обратная матрица:
[[-0.0893871   0.04411828  0.18110753 -0.15255914]
 [-0.00572581  0.01459677  0.03395161 -0.03354839]
 [ 0.13477419 -0.09090323 -0.21154839  0.19445161]
 [-0.06877419  0.04490323  0.08554839 -0.07845161]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [81]:
el0 = np.where(D_inv < 0)
el1 = np.where(D_inv > 0)
D_inv[el0], D_inv[el1]

(array([-0.0893871 , -0.15255914, -0.00572581, -0.03354839, -0.09090323,
        -0.21154839, -0.06877419, -0.07845161]),
 array([0.04411828, 0.18110753, 0.01459677, 0.03395161, 0.13477419,
        0.19445161, 0.04490323, 0.08554839]))

In [82]:
D_inv[el0] = 0
D_inv[el1] = 1
D_inv

array([[0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.]])

In [91]:
E = np.where(D_inv == 1, B, C)
E

array([[ 13,  14,  23,   8],
       [ 13,  50,  86,  10],
       [ 23,   7,  11, 212],
       [  8, 122, 212,   8]])